name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for production
      run: npm run build
      env:
        NODE_ENV: production
        
    - name: Deploy to production branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # production ブランチへデプロイ
        git fetch origin
        if git rev-parse --verify origin/production >/dev/null 2>&1; then
          git checkout -B production origin/production
        else
          git checkout --orphan production
        fi
        
        git rm -rf . 2>/dev/null || true
        cp -r dist/* .
        git add .
        
        if ! git diff --staged --quiet; then
          git commit -m "Production deploy - $(date)"
          git push -f origin production
        fi
